<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'category_id'       => 1,
                'sku'               => 'OLI-TOP1-5W30',
                'name'              => 'Oli TOP 1 5W-30',
                'description'       => 'Oli mesin sintetik untuk mobil bensin',
                'unit'              => 'liter',
                'purchase_price'    => 75000,
                'selling_price'     => 95000,
                'stock_quantity'    => 50,
                'min_stock'         => 10,
                'max_stock'         => 100,
                'reorder_point'     => 15,
                'reorder_quantity'  => 30,
                'avg_daily_usage'   => 2.5,
                'lead_time_days'    => 3,
                'brand'             => 'TOP 1',
                'compatible_vehicles' => 'Toyota, Honda, Suzuki',
                'is_active'         => true,
            ],
            [
                'category_id'       => 1,
                'sku'               => 'OLI-SHE-10W40',
                'name'              => 'Oli Shell Helix HX7 10W-40',
                'description'       => 'Oli mesin semi sintetik',
                'unit'              => 'liter',
                'purchase_price'    => 65000,
                'selling_price'     => 85000,
                'stock_quantity'    => 40,
                'min_stock'         => 10,
                'max_stock'         => 80,
                'reorder_point'     => 15,
                'reorder_quantity'  => 25,
                'avg_daily_usage'   => 2,
                'lead_time_days'    => 3,
                'brand'             => 'Shell',
                'compatible_vehicles' => 'All vehicles',
                'is_active'         => true,
            ],
            [
                'category_id'       => 2,
                'sku'               => 'FIL-OLI-TOY',
                'name'              => 'Filter Oli Toyota Avanza',
                'description'       => 'Filter oli original untuk Toyota Avanza/Xenia',
                'unit'              => 'pcs',
                'purchase_price'    => 35000,
                'selling_price'     => 50000,
                'stock_quantity'    => 30,
                'min_stock'         => 5,
                'max_stock'         => 50,
                'reorder_point'     => 10,
                'reorder_quantity'  => 20,
                'avg_daily_usage'   => 1.5,
                'lead_time_days'    => 2,
                'brand'             => 'Toyota Genuine Parts',
                'compatible_vehicles' => 'Toyota Avanza, Daihatsu Xenia',
                'is_active'         => true,
            ],
            [
                'category_id'       => 2,
                'sku'               => 'FIL-UDA-HON',
                'name'              => 'Filter Udara Honda Jazz',
                'description'       => 'Filter udara original Honda Jazz',
                'unit'              => 'pcs',
                'purchase_price'    => 45000,
                'selling_price'     => 65000,
                'stock_quantity'    => 25,
                'min_stock'         => 5,
                'max_stock'         => 40,
                'reorder_point'     => 8,
                'reorder_quantity'  => 15,
                'avg_daily_usage'   => 1,
                'lead_time_days'    => 3,
                'brand'             => 'Honda Genuine Parts',
                'compatible_vehicles' => 'Honda Jazz, Honda City',
                'is_active'         => true,
            ],
            [
                'category_id'       => 3,
                'sku'               => 'BRK-PAD-AVZ',
                'name'              => 'Kampas Rem Depan Avanza',
                'description'       => 'Kampas rem depan Toyota Avanza/Xenia',
                'unit'              => 'set',
                'purchase_price'    => 120000,
                'selling_price'     => 165000,
                'stock_quantity'    => 20,
                'min_stock'         => 5,
                'max_stock'         => 30,
                'reorder_point'     => 8,
                'reorder_quantity'  => 10,
                'avg_daily_usage'   => 0.8,
                'lead_time_days'    => 3,
                'brand'             => 'Bendix',
                'compatible_vehicles' => 'Toyota Avanza, Daihatsu Xenia',
                'is_active'         => true,
            ],
            [
                'category_id'       => 3,
                'sku'               => 'BRK-PAD-CRV',
                'name'              => 'Kampas Rem Depan Honda CRV',
                'description'       => 'Kampas rem depan Honda CRV',
                'unit'              => 'set',
                'purchase_price'    => 180000,
                'selling_price'     => 240000,
                'stock_quantity'    => 15,
                'min_stock'         => 4,
                'max_stock'         => 25,
                'reorder_point'     => 6,
                'reorder_quantity'  => 10,
                'avg_daily_usage'   => 0.5,
                'lead_time_days'    => 3,
                'brand'             => 'Brembo',
                'compatible_vehicles' => 'Honda CRV',
                'is_active'         => true,
            ],
            [
                'category_id'       => 4,
                'sku'               => 'BAT-GS-NS60',
                'name'              => 'Aki GS Astra NS60',
                'description'       => 'Aki kering 12V 45Ah',
                'unit'              => 'pcs',
                'purchase_price'    => 450000,
                'selling_price'     => 580000,
                'stock_quantity'    => 12,
                'min_stock'         => 3,
                'max_stock'         => 20,
                'reorder_point'     => 5,
                'reorder_quantity'  => 8,
                'avg_daily_usage'   => 0.4,
                'lead_time_days'    => 5,
                'brand'             => 'GS Astra',
                'compatible_vehicles' => 'Toyota Avanza, Daihatsu Xenia, Honda Jazz',
                'is_active'         => true,
            ],
            [
                'category_id'       => 4,
                'sku'               => 'BAT-YUA-NS70',
                'name'              => 'Aki Yuasa NS70',
                'description'       => 'Aki basah 12V 65Ah',
                'unit'              => 'pcs',
                'purchase_price'    => 550000,
                'selling_price'     => 720000,
                'stock_quantity'    => 10,
                'min_stock'         => 3,
                'max_stock'         => 15,
                'reorder_point'     => 4,
                'reorder_quantity'  => 6,
                'avg_daily_usage'   => 0.3,
                'lead_time_days'    => 5,
                'brand'             => 'Yuasa',
                'compatible_vehicles' => 'Honda CRV, Toyota Innova',
                'is_active'         => true,
            ],
            [
                'category_id'       => 5,
                'sku'               => 'TIR-BRI-185',
                'name'              => 'Ban Bridgestone 185/65 R15',
                'description'       => 'Ban Bridgestone Turanza',
                'unit'              => 'pcs',
                'purchase_price'    => 520000,
                'selling_price'     => 680000,
                'stock_quantity'    => 16,
                'min_stock'         => 4,
                'max_stock'         => 24,
                'reorder_point'     => 6,
                'reorder_quantity'  => 8,
                'avg_daily_usage'   => 0.6,
                'lead_time_days'    => 3,
                'brand'             => 'Bridgestone',
                'compatible_vehicles' => 'Honda Jazz, Toyota Vios',
                'is_active'         => true,
            ],
            [
                'category_id'       => 5,
                'sku'               => 'TIR-MIC-205',
                'name'              => 'Ban Michelin 205/55 R16',
                'description'       => 'Ban Michelin Primacy',
                'unit'              => 'pcs',
                'purchase_price'    => 780000,
                'selling_price'     => 980000,
                'stock_quantity'    => 12,
                'min_stock'         => 4,
                'max_stock'         => 20,
                'reorder_point'     => 6,
                'reorder_quantity'  => 8,
                'avg_daily_usage'   => 0.4,
                'lead_time_days'    => 5,
                'brand'             => 'Michelin',
                'compatible_vehicles' => 'Honda CRV, Toyota Camry',
                'is_active'         => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
